name: healthie_connector
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: default

vars:
  exclude_packages: ["all"]
  ## The Tuva Project vars
  ### Uncomment the line(s) based on the type of source data.
  #claims_enabled: true
  #clinical_enabled: true
  #provider_attribution_enabled: true

  ## CMS HCC data mart vars
  # Setting the payment year to year needed for the demo data
  #cms_hcc_payment_year: 2018

  ## Quality Measure data mart vars
  ### Setting the reporting period to date needed for demo data
  #quality_measures_period_end: "2018-12-31"


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

seeds:
  dbt_project_evaluator:
    dbt_project_evaluator_exceptions:
      +enabled: false

models:
  healthie_connector:
    staging:
      +materialized: table
      +schema: _input_layer
      +tags: input_layer
    intermediate:
      +materialized: table
      +schema: _input_layer
      +tags: input_layer
    final:
      +materialized: table
      +schema: input_layer
      +tags: input_layer
  dbt_project_evaluator:
    marts:
      dag:
        fct_model_fanout:
          +enabled: false
        fct_root_models:
          +enabled: false
        fct_direct_join_to_source:
          +enabled: false
        fct_marts_or_intermediate_dependent_on_source:
          +enabled: false
        fct_multiple_sources_joined:
          +enabled: false
        fct_staging_dependent_on_staging:
          +enabled: false
        fct_too_many_joins:
          +enabled: false
      documentation:
        +enabled: false
      tests:
        fct_sources_without_freshness:
          +enabled: false
        fct_test_coverage:
          +enabled: false
      structure:
        fct_test_directories:
          +enabled: false
        fct_source_directories:
          +enabled: false
        fct_model_directories:
          +enabled: false
      performance:
        +enabled: false
      governance:
        +enabled: false

data_tests:
  dbt_project_evaluator:
    +severity: error

dispatch:
  - macro_namespace: dbt
    search_order: ['dbt_project_evaluator', 'dbt']


