select
    cast(accept_assignment as {{ dbt.type_boolean() }}) as accept_assignment
    ,cast(additional_text as {{ dbt.type_string() }}) as additional_text
    ,cast(adjustment as {{ dbt.type_string() }}) as adjustment
    ,cast(amount_paid as {{ dbt.type_string() }}) as amount_paid
    ,cast(amount_reimbursed as {{ dbt.type_string() }}) as amount_reimbursed
    ,cast(billing_provider_id as {{ dbt.type_string() }}) as billing_provider_id
    ,cast(check_numbers as {{ dbt.type_string() }}) as check_numbers
    ,cast(claim_md_rejection_messages as {{ dbt.type_string() }}) as claim_md_rejection_messages
    ,cast(claim_md_rejection_messages_info as {{ dbt.type_string() }}) as claim_md_rejection_messages_info
    ,cast(claim_submissions as {{ dbt.type_string() }}) as claim_submissions
    ,cast(client_responsibility as {{ dbt.type_string() }}) as client_responsibility
    ,cast(client_responsibility_removed as {{ dbt.type_boolean() }}) as client_responsibility_removed
    ,cast(client_sig_on_file as {{ dbt.type_boolean() }}) as client_sig_on_file
    ,cast(cms1500_policies as {{ dbt.type_string() }}) as cms1500_policies
    ,cast(copay as {{ dbt.type_string() }}) as copay
    ,cast(copay_still_owed as {{ dbt.type_string() }}) as copay_still_owed
    ,cast(cpt_code_names as {{ dbt.type_string() }}) as cpt_code_names
    ,cast(cpt_codes_cms1500s as {{ dbt.type_string() }}) as cpt_codes_cms1500s
    ,cast(created_at as {{ dbt.type_string() }}) as created_at
    ,cast(cursor as {{ dbt.type_string() }}) as cursor
    ,cast(date_of_service as {{ dbt.type_string() }}) as date_of_service
    ,cast(dietitian_id as {{ dbt.type_string() }}) as dietitian_id
    ,cast(eras as {{ dbt.type_string() }}) as eras
    ,cast(estimated_cpt_fees_for_user as {{ dbt.type_string() }}) as estimated_cpt_fees_for_user
    ,cast(form_answer_group_id as {{ dbt.type_string() }}) as form_answer_group_id
    ,cast(has_been_submitted as {{ dbt.type_boolean() }}) as has_been_submitted
    ,cast(icd_codes_cms1500s as {{ dbt.type_string() }}) as icd_codes_cms1500s
    ,cast(id as {{ dbt.type_string() }}) as id
    ,cast(include_referrer_information as {{ dbt.type_boolean() }}) as include_referrer_information
    ,cast(insured_sig_on_file as {{ dbt.type_boolean() }}) as insured_sig_on_file
    ,cast(nineteen_reserved as {{ dbt.type_string() }}) as nineteen_reserved
    ,cast(org_info as {{ dbt.type_string() }}) as org_info
    ,cast(organization_info_id as {{ dbt.type_string() }}) as organization_info_id
    ,cast(orig_ref_number as {{ dbt.type_string() }}) as orig_ref_number
    ,cast(paid_out_at as {{ dbt.type_string() }}) as paid_out_at
    ,cast(patient as {{ dbt.type_string() }}) as patient
    ,cast(patient_account_num as {{ dbt.type_string() }}) as patient_account_num
    ,cast(patient_id as {{ dbt.type_string() }}) as patient_id
    ,cast(primary_plan_name as {{ dbt.type_string() }}) as primary_plan_name
    ,cast(reasons as {{ dbt.type_string() }}) as reasons
    ,cast(referral_info as {{ dbt.type_string() }}) as referral_info
    ,cast(reimbursed_at as {{ dbt.type_string() }}) as reimbursed_at
    ,cast(rendering_provider as {{ dbt.type_string() }}) as rendering_provider
    ,cast(rendering_provider_other_id as {{ dbt.type_string() }}) as rendering_provider_other_id
    ,cast(rendering_provider_other_id_object as {{ dbt.type_string() }}) as rendering_provider_other_id_object
    ,cast(resubmission_code as {{ dbt.type_string() }}) as resubmission_code
    ,cast(service_location as {{ dbt.type_string() }}) as service_location
    ,cast(service_location_id as {{ dbt.type_string() }}) as service_location_id
    ,cast(status as {{ dbt.type_string() }}) as status
    ,cast(tend_reserved as {{ dbt.type_string() }}) as tend_reserved
    ,cast(total_charge as {{ dbt.type_string() }}) as total_charge
    ,cast(updated_at as {{ dbt.type_string() }}) as updated_at
    ,cast(updated_by_sftp as {{ dbt.type_boolean() }}) as updated_by_sftp
    ,cast(use_indiv_npi as {{ dbt.type_boolean() }}) as use_indiv_npi
from {{ source('healthie', 'cms_1500') }}
