select
    cast(id as {{ dbt.type_int() }}) as id
    , cast(a.date as {{ dbt.type_timestamp() }}) as appointment_date
    , cast(user_id as {{ dbt.type_int() }}) as user_id
    , cast(other_party_id as {{ dbt.type_int() }}) as other_party_id
    , cast(created_at as {{ dbt.type_timestamp() }}) as created_at
    , cast(updated_at as {{ dbt.type_timestamp() }}) as updated_at
    , cast(confirmed as {{ dbt.type_boolean() }}) as confirmed
    , cast(a.length as {{ dbt.type_int() }}) as appointment_length
    , cast(contact_type as {{ dbt.type_string() }}) as contact_type
    , cast(reason as {{ dbt.type_string() }}) as reason
    , cast(appointment_type_id as {{ dbt.type_int() }}) as appointment_type_id
    , cast(a.location as {{ dbt.type_string() }}) as appointment_location
    , cast(actual_duration as {{ dbt.type_int() }}) as actual_duration
    , cast(pm_status as {{ dbt.type_string() }}) as pm_status
    , cast(deleted_at as {{ dbt.type_timestamp() }}) as deleted_at
    , cast(max_attendees as {{ dbt.type_int() }}) as max_attendees
    , cast(appointment_category as {{ dbt.type_string() }}) as appointment_category
    , cast(appointment_inclusions_count as {{ dbt.type_int() }}) as appointment_inclusions_count
    , cast(notes as {{ dbt.type_string() }}) as notes
    , cast(external_id as {{ dbt.type_string() }}) as external_id
    , cast(external_id_type as {{ dbt.type_string() }}) as external_id_type
    , cast(appointment_location_id as {{ dbt.type_int() }}) as appointment_location_id
    , cast(zoom_start_url as {{ dbt.type_string() }}) as zoom_start_url
    , cast(zoom_join_url as {{ dbt.type_string() }}) as zoom_join_url
    , cast(is_zoom_chat as {{ dbt.type_boolean() }}) as is_zoom_chat
    , cast(client_confirmed as {{ dbt.type_boolean() }}) as client_confirmed
    , cast(recurring_appointment_id as {{ dbt.type_int() }}) as recurring_appointment_id
    , cast(time_recurring_override as {{ dbt.type_boolean() }}) as time_recurring_override
    , cast(is_blocker as {{ dbt.type_boolean() }}) as is_blocker
    , cast(room_id as {{ dbt.type_int() }}) as room_id
    , cast(pm_status_changed_at as {{ dbt.type_timestamp() }}) as pm_status_changed_at
    , cast(active_appointment_inclusions_count as {{ dbt.type_int() }}) as active_appointment_inclusions_count
    , cast(pending_appointment_inclusions_count as {{ dbt.type_int() }}) as pending_appointment_inclusions_count
    , cast(creator_id as {{ dbt.type_int() }}) as creator_id
    , cast(provider_inclusions_count as {{ dbt.type_int() }}) as provider_inclusions_count
    , cast(patient_reschedule_count as {{ dbt.type_int() }}) as patient_reschedule_count
    , cast(external_videochat_url as {{ dbt.type_string() }}) as external_videochat_url
    , cast(price as {{ dbt.type_numeric() }}) as price
    , cast(cpt_code_id as {{ dbt.type_int() }}) as cpt_code_id
    , cast(units as {{ dbt.type_int() }}) as units
    , cast(metadata as {{ dbt.type_string() }}) as metadata
    , cast(pm_status_last_changed_by_id as {{ dbt.type_int() }}) as pm_status_last_changed_by_id
    , cast(last_updated_by_id as {{ dbt.type_int() }}) as last_updated_by_id
    , cast(late_cancellation_fee as {{ dbt.type_numeric() }}) as late_cancellation_fee
    , cast(no_show_fee as {{ dbt.type_numeric() }}) as no_show_fee
    , cast(insurance_billing_enabled as {{ dbt.type_boolean() }}) as insurance_billing_enabled
from {{ source('healthie', 'appointment') }} as a