select
    cast(active_care_team_members as {{ dbt.type_string() }}) as active_care_team_members
    ,cast(active_members_for_conversation as {{ dbt.type_string() }}) as active_members_for_conversation
    ,cast(appas as {{ dbt.type_int() }}) as appas
    ,cast(can_have_suborgs as {{ dbt.type_boolean() }}) as can_have_suborgs
    ,cast(cancellation_reasons as {{ dbt.type_string() }}) as cancellation_reasons
    ,cast(created_at as {{ dbt.type_string() }}) as created_at
    ,cast(default_pdf_letterhead_template as {{ dbt.type_string() }}) as default_pdf_letterhead_template
    ,cast(e_labs_settings as {{ dbt.type_string() }}) as e_labs_settings
    ,cast(id as {{ dbt.type_string() }}) as id
    ,cast(insurance_plans_used_by_organization_providers as {{ dbt.type_string() }}) as insurance_plans_used_by_organization_providers
    ,cast(is_using_system_default_pdf_letterhead_template as {{ dbt.type_boolean() }}) as is_using_system_default_pdf_letterhead_template
    ,cast(location as {{ dbt.type_string() }}) as location
    ,cast(name as {{ dbt.type_string() }}) as name
    ,cast(npi as {{ dbt.type_string() }}) as npi
    ,cast(num_users as {{ dbt.type_string() }}) as num_users
    ,cast(onboarding_flow_id as {{ dbt.type_int() }}) as onboarding_flow_id
    ,cast(only_active_organization_memberships as {{ dbt.type_string() }}) as only_active_organization_memberships
    ,cast(only_active_providers as {{ dbt.type_string() }}) as only_active_providers
    ,cast(only_active_providers_count as {{ dbt.type_int() }}) as only_active_providers_count
    ,cast(only_active_support as {{ dbt.type_string() }}) as only_active_support
    ,cast(only_active_support_count as {{ dbt.type_int() }}) as only_active_support_count
    ,cast(org_roles as {{ dbt.type_string() }}) as org_roles
    ,cast(organization_cpt_codes as {{ dbt.type_string() }}) as organization_cpt_codes
    ,cast(organization_email as {{ dbt.type_string() }}) as organization_email
    ,cast(organization_info as {{ dbt.type_string() }}) as organization_info
    ,cast(organization_infos as {{ dbt.type_string() }}) as organization_infos
    ,cast(organization_infos_count as {{ dbt.type_int() }}) as organization_infos_count
    ,cast(organization_memberships as {{ dbt.type_string() }}) as organization_memberships
    ,cast(organization_memberships_count as {{ dbt.type_int() }}) as organization_memberships_count
    ,cast(other_id as {{ dbt.type_string() }}) as other_id
    ,cast(other_id_qual as {{ dbt.type_string() }}) as other_id_qual
    ,cast(owner as {{ dbt.type_string() }}) as owner
    ,cast(owner_id as {{ dbt.type_string() }}) as owner_id
    ,cast(owner_subscription as {{ dbt.type_string() }}) as owner_subscription
    ,cast(parent_organization as {{ dbt.type_string() }}) as parent_organization
    ,cast(parent_organization_id as {{ dbt.type_string() }}) as parent_organization_id
    ,cast(pdf_letterhead_templates as {{ dbt.type_string() }}) as pdf_letterhead_templates
    ,cast(permission_templates as {{ dbt.type_string() }}) as permission_templates
    ,cast(phone_number as {{ dbt.type_string() }}) as phone_number
    ,cast(providers as {{ dbt.type_string() }}) as providers
    ,cast(providers_count as {{ dbt.type_int() }}) as providers_count
    ,cast(rupa_health_members as {{ dbt.type_string() }}) as rupa_health_members
    ,cast(state_licenses as {{ dbt.type_string() }}) as state_licenses
    ,cast(suborganizations as {{ dbt.type_string() }}) as suborganizations
    ,cast(tags as {{ dbt.type_string() }}) as tags
    ,cast(tax_id as {{ dbt.type_string() }}) as tax_id
    ,cast(tax_id_type as {{ dbt.type_string() }}) as tax_id_type
    ,cast(user_groups as {{ dbt.type_string() }}) as user_groups
    ,cast(users as {{ dbt.type_string() }}) as users
    ,cast(zus_builder_id as {{ dbt.type_string() }}) as zus_builder_id
from {{ source('healthie', 'organization') }}