select
    cast(id as {{ dbt.type_int() }}) as id
    , cast(email as {{ dbt.type_string() }}) as email
    , cast(created_at as {{ dbt.type_timestamp() }}) as created_at
    , cast(updated_at as {{ dbt.type_timestamp() }}) as updated_at
    , cast(gender as {{ dbt.type_string() }}) as gender
    , cast(first_name as {{ dbt.type_string() }}) as first_name
    , cast(last_name as {{ dbt.type_string() }}) as last_name
    , cast(dob as date) as dob
    , cast(dietitian_id as {{ dbt.type_int() }}) as dietitian_id
    , cast(height as {{ dbt.type_numeric() }}) as height
    , cast(avatar_file_name as {{ dbt.type_string() }}) as avatar_file_name
    , cast(avatar_content_type as {{ dbt.type_string() }}) as avatar_content_type
    , cast(avatar_file_size as {{ dbt.type_int() }}) as avatar_file_size
    , cast(avatar_updated_at as {{ dbt.type_timestamp() }}) as avatar_updated_at
    , cast(stripe_id as {{ dbt.type_string() }}) as stripe_id
    , cast(unique_code as {{ dbt.type_string() }}) as unique_code
    , cast(phone_number as {{ dbt.type_string() }}) as phone_number
    , cast(tax_id as {{ dbt.type_string() }}) as tax_id
    , cast(npi as {{ dbt.type_string() }}) as npi
    , cast(license_num as {{ dbt.type_string() }}) as license_num
    , cast(seen_welcome as {{ dbt.type_boolean() }}) as seen_welcome
    , cast(ssn as {{ dbt.type_string() }}) as ssn
    , cast(other_id_qualifier as {{ dbt.type_string() }}) as other_id_qualifier
    , cast(qualifications as {{ dbt.type_string() }}) as qualifications
    , cast(other_id as {{ dbt.type_string() }}) as other_id
    , cast(active as {{ dbt.type_boolean() }}) as active
    , cast(used_code as {{ dbt.type_string() }}) as used_code
    , cast(user_group_id as {{ dbt.type_int() }}) as user_group_id
    , cast(timezone as {{ dbt.type_string() }}) as timezone
    , cast(deleted_at as {{ dbt.type_timestamp() }}) as deleted_at
    , cast(default_currency as {{ dbt.type_string() }}) as default_currency
    , cast(quick_notes as {{ dbt.type_string() }}) as quick_notes
    , cast(skipped_email as {{ dbt.type_boolean() }}) as skipped_email
    , cast(lock_timezone as {{ dbt.type_boolean() }}) as lock_timezone
    , cast(record_identifier as {{ dbt.type_string() }}) as record_identifier
    , cast(additional_phone_number as {{ dbt.type_string() }}) as additional_phone_number
    , cast(has_completed_intake_forms as {{ dbt.type_boolean() }}) as has_completed_intake_forms
    , cast(blast_seen as {{ dbt.type_boolean() }}) as blast_seen
    , cast(activity_level as {{ dbt.type_string() }}) as activity_level
    , cast(seen_onboarding_complete_page as {{ dbt.type_boolean() }}) as seen_onboarding_complete_page
    , cast(next_appt_date as {{ dbt.type_timestamp() }}) as next_appt_date
    , cast(legal_name as {{ dbt.type_string() }}) as legal_name
    , cast(fullscript_practitioner_id as {{ dbt.type_string() }}) as fullscript_practitioner_id
    , cast(last_active as {{ dbt.type_timestamp() }}) as last_active
    , cast(active_care_plan_id as {{ dbt.type_int() }}) as active_care_plan_id
    , cast(consented_to_labs as {{ dbt.type_boolean() }}) as consented_to_labs
    , cast(scheduling_priority as {{ dbt.type_int() }}) as scheduling_priority
    , cast(default_stripe_customer_detail_id as {{ dbt.type_int() }}) as default_stripe_customer_detail_id
    , cast(sex as {{ dbt.type_string() }}) as sex
    , cast(gender_identity as {{ dbt.type_string() }}) as gender_identity
    , cast(dosespot_patient_id as {{ dbt.type_string() }}) as dosespot_patient_id
    , cast(living_plate_meal_plan_id as {{ dbt.type_string() }}) as living_plate_meal_plan_id
    , cast(living_plate_user_id as {{ dbt.type_string() }}) as living_plate_user_id
    , cast(dismissed_lock_charting_note_warning as {{ dbt.type_boolean() }}) as dismissed_lock_charting_note_warning
    , cast(permanently_disable_tz_prompt as {{ dbt.type_boolean() }}) as permanently_disable_tz_prompt
    , cast(pronouns as {{ dbt.type_string() }}) as pronouns
    , cast(devices_unavailability as {{ dbt.type_boolean() }}) as devices_unavailability
    , cast(primary_ethnicity_code as {{ dbt.type_int() }}) as primary_ethnicity_code
    , cast(secondary_ethnicity_code as {{ dbt.type_int() }}) as secondary_ethnicity_code
    , cast(gender_identity_code as {{ dbt.type_string() }}) as gender_identity_code
    , cast(preferred_language_code as {{ dbt.type_string() }}) as preferred_language_code
    , cast(primary_race_code as {{ dbt.type_string() }}) as primary_race_code
    , cast(secondary_race_code as {{ dbt.type_string() }}) as secondary_race_code
    , cast(dismissed_charting_note_addendum_warning as {{ dbt.type_boolean() }}) as dismissed_charting_note_addendum_warning
    , cast(sexual_orientation_code as {{ dbt.type_string() }}) as sexual_orientation_code
    , cast(rupa_patient_id as {{ dbt.type_string() }}) as rupa_patient_id
    , cast(primary_ethnicity as {{ dbt.type_string() }}) as primary_ethnicity
    , cast(secondary_ethnicity as {{ dbt.type_string() }}) as secondary_ethnicity
    , cast(additional_record_identifier as {{ dbt.type_string() }}) as additional_record_identifier
    , cast(metadata as {{ dbt.type_string() }}) as metadata
    , cast(archived_at as {{ dbt.type_timestamp() }}) as archived_at
    , cast(auto_charge_enabled as {{ dbt.type_boolean() }}) as auto_charge_enabled
    , cast(sexual_orientation_other as {{ dbt.type_string() }}) as sexual_orientation_other
    , cast(is_provider as {{ dbt.type_boolean() }}) as is_provider
    , cast(dismissed_insurance_eligibility_warning as {{ dbt.type_boolean() }}) as dismissed_insurance_eligibility_warning
    , cast(new_course_item_last_notified_at as {{ dbt.type_timestamp() }}) as new_course_item_last_notified_at
    , cast(default_dosespot_clinic_id as {{ dbt.type_string() }}) as default_dosespot_clinic_id
from {{ source('healthie', 'user') }}
